language: ruby
rvm:
  - 2.2.2
  - jruby
before_install:
  - gem install bundler
  - mysql -e 'create database ruby_simple_search_test;'
  - psql -c 'create database ruby_simple_search_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
