language: ruby
rvm:
  - 2.2.4
gemfile:
  - Gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
sudo: false
script:
  - ruby test/sqlite_test.rb
  - ruby test/mysql_test.rb
  - ruby test/postgresql_test.rb
before_install:
  - gem install bundler
  - mysql -e 'create database ruby_simple_search_test;'
  - psql -c 'create database ruby_simple_search_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
